# Generated by Django 5.0.3 on 2024-12-07 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pationt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/doctors/profile_pics')),
                ('field', models.CharField(blank=True, choices=[('فردی', 'فردی'), ('زوج', 'زوج'), ('کودک', 'کودک'), ('نوجوان', 'نوجوان'), ('تحصیلی', 'تحصیلی'), ('خانواده', 'خانواده')], default='defualt', max_length=255, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('clinic_telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('doctorate_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
