# Generated by Django 5.0.3 on 2024-12-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_psychiatrist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychiatrist',
            name='field',
            field=models.CharField(blank=True, choices=[('فردی', 'فردی'), ('زوج', 'زوج'), ('کودک', 'کودک'), ('نوجوان', 'نوجوان'), ('تحصیلی', 'تحصیلی'), ('خانواده', 'خانواده'), ('کوچینگ', 'کوچینگ'), ('بالینی', 'بالینی'), ('روان پزشکی', 'روان پزشکی')], default='defualt', max_length=255, null=True),
        ),
    ]
