# Generated by Django 5.0.3 on 2024-12-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_remove_psychiatrist_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychiatrist',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychiatrist',
            name='clinic_telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='psychiatrist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
