# Generated by Django 5.1.4 on 2024-12-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_alter_psychiatrist_field'),
        ('counseling', '0004_psychiatrist_clinic_address_and_more'),
    ]

    operations = [
    ]
