# Generated by Django 5.0.3 on 2024-12-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0002_psychiatrist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPersonalityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.TextField(max_length=600)),
                ('psychiatrist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counseling.psychiatrist')),
            ],
        ),
    ]
