# Generated by Django 5.0.3 on 2024-12-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('MeetingLink', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی')], max_length=15)),
                ('day', models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یک\u200cشنبه'), ('دوشنبه', 'دو\u200cشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهار\u200cشنبه'), ('پنج\u200cشنبه', 'پنج\u200cشنبه'), ('جمعه', 'جمعه')], max_length=10)),
                ('pationt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pationt_reservations', to='counseling.pationt')),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatrist_reservations', to='counseling.psychiatrist')),
            ],
            options={
                'unique_together': {('date', 'time', 'pationt', 'psychiatrist')},
            },
        ),
    ]
