# Generated by Django 5.0.3 on 2024-12-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0)),
                ('comments', models.TextField(blank=True)),
                ('pationt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.pationt')),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.psychiatrist')),
            ],
            options={
                'unique_together': {('psychiatrist', 'pationt')},
            },
        ),
    ]
