# Generated by Django 5.0.3 on 2024-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0004_alter_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
