# Generated by Django 5.0.3 on 2024-12-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depression_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conmessage',
            name='disorder',
            field=models.JSONField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conmessage',
            name='emotion',
            field=models.JSONField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conmessage',
            name='message',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conmessage',
            name='validation',
            field=models.JSONField(blank=True, unique=True),
        ),
    ]
