# Generated by Django 5.1.4 on 2024-12-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('symptoms', models.JSONField()),
                ('preferred_therapy_methods', models.JSONField(blank=True, null=True)),
                ('presentation_preference', models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50)),
                ('communication_preference', models.JSONField(blank=True, null=True)),
                ('therapist_gender_preference', models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50)),
                ('religion_preference', models.CharField(choices=[('مذهبی', 'مذهبی'), ('غیرمذهبی', 'غیرمذهبی'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50)),
                ('treatment_duration', models.CharField(choices=[('کوتاه\u200cمدت', 'کوتاه\u200cمدت'), ('بلندمدت', 'بلندمدت')], max_length=50)),
                ('stress_level', models.IntegerField()),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('past_treatments', models.TextField(blank=True, null=True)),
                ('suicidal_thoughts', models.CharField(choices=[('هرگز', 'هرگز'), ('یک ماه پیش', 'یک ماه پیش'), ('هفته گذشته', 'هفته گذشته'), ('همین حالا', 'همین حالا')], max_length=50)),
                ('physical_issues', models.TextField(blank=True, null=True)),
                ('sleep_hours', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.CharField(choices=[('کم', 'کم'), ('متوسط', 'متوسط'), ('زیاد', 'زیاد')], max_length=50)),
                ('social_activities', models.BooleanField(default=False)),
                ('expectations', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.JSONField()),
                ('therapy_methods', models.JSONField()),
                ('age_groups', models.JSONField()),
                ('session_preference', models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی'), ('هر دو', 'هر دو')], max_length=50)),
                ('communication_preference', models.JSONField(blank=True, null=True)),
                ('religion', models.CharField(choices=[('مذهبی', 'مذهبی'), ('غیرمذهبی', 'غیرمذهبی'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50)),
                ('gender', models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50)),
                ('experience_years', models.IntegerField()),
                ('max_sessions_per_week', models.IntegerField(blank=True, null=True)),
                ('prefers_religious_patients', models.CharField(blank=True, choices=[('مذهبی', 'مذهبی'), ('غیرمذهبی', 'غیرمذهبی'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50, null=True)),
                ('prefers_gender', models.CharField(blank=True, choices=[('زن', 'زن'), ('مرد', 'مرد'), ('فرقی نمی\u200cکند', 'فرقی نمی\u200cکند')], max_length=50, null=True)),
                ('physical_conditions_experience', models.BooleanField(default=False)),
                ('crisis_management', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
