# Generated by Django 5.0.3 on 2024-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
