# Generated by Django 5.0.3 on 2024-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctorate_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
