# Generated by Django 5.0.3 on 2024-12-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_doctorate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clinic_telephone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='doctorate_code',
        ),
    ]
