name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
      run: docker-compose -f BackEnd/docker-compose.yml up -d
    - name: Run Tests
      run: docker exec sh -c "pytest ."
      # ///////////////
  
