name: Django CI/CD  
on:  
  push:  
    branches: [ main ] 

jobs:  
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [postgres]
        python-version: ["3.10"]  # Specify a Python version that is available
        include:
          - db: postgres
            db_port: 5432
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Hgbr@@5391
          POSTGRES_DB: TherapyDB
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3  # Use v2 with a more recent Python version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      working-directory: BackEnd
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      working-directory: BackEnd
      run: pip install -r requirements.txt

    - name: Check Database Connection
      working-directory: BackEnd
      run: |
        python -c "
        import psycopg2
        try:
            conn = psycopg2.connect(
                dbname='TherapyDB',
                user='postgres',
                password='Hgbr@@5391',
                host='localhost',
                port='5432'
            )
            conn.close()
            print('Database connection successful!')
        except Exception as e:
            print('Database connection error:', str(e))
            exit(1)
        "
    - name: Run tests
      working-directory: BackEnd
      env:
          DB: ${{ matrix.db }}
          DB_HOST: 'localhost'
          DB_PORT: ${{ matrix.db_port }}
          DB_PASSWORD: Hgbr@@5391
          DB_NAME: 'TherapyDB'
          DB_USER: 'postgres'
          WEBSITE_URL: 'localhost'
      run: pytest

  # Deploy:  
  #   needs: build-and-test  # This ensures that deploy job runs only if build job succeeds  
  #   name: deploy  
  #   runs-on: ubuntu-latest  
  #   steps:  
  #     - uses: actions/checkout@v2  
  #     - name: Connect  
  #       uses: appleboy/ssh-action@master  
  #       with:  
  #         username: ${{ secrets.USERNAME }}  
  #         password: ${{ secrets.PASSWORD }}  
  #         host: ${{ secrets.HOST }}  
  #         port: ${{ secrets.PORT }}  
  #         script: |  
  #           cd /root/Back-End
  #           docker compose down  
  #           git pull  
  #           docker compose up --build -d
