name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Hgbr@@5391
          POSTGRES_DB: TherapyDB
        ports:
          - 5432:5432

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4
          
      # Debugging Step
      - name: Debug Secrets
        run: |
          echo "Checking PostgreSQL user: $POSTGRES_USER"
          echo "Database name is set as $POSTGRES_DB"

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3.1: Debug current directory and list files
      - name: List files and print working directory
        working-directory: BackEnd
        run: |
          echo "Current working directory:" $(pwd)
          echo "Files in the directory:"
          ls -la

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: BackEnd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Debugging Step
      - name: Debug Secrets
        run: |
          echo "Checking PostgreSQL user: $POSTGRES_USER"
          echo "Database name is set as $POSTGRES_DB"

      # Step 6: Run migrations and tests
      - name: Run Tests
        working-directory: BackEnd
        env:
          DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB
        run: |
          python manage.py migrate
          python manage.py test
